/*
 * File generated by Test generator (dotup.dotup-vscode-test-generator)
 * Date: 2019-03-19 14:20:20
*/
import { expect } from 'chai';
import { Question } from '../src/questions/Question';

describe('Test class Question', () => {

  it('Should create instance', () => {
    // Arguments
    const name1 = 'Oha';

    // Method call
    const question = new Question(name1);

    // Expect result
    expect(question).instanceOf(Question)
    expect(question.name).equals(name1);
  });

});
